# Generated by Django 4.1.7 on 2023-02-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=140)),
                ('lastname', models.CharField(max_length=140)),
                ('age', models.IntegerField(max_length=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastaname', models.CharField(max_length=140)),
                ('firstname', models.CharField(max_length=140)),
                ('age', models.IntegerField(max_length=99, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('duration', models.FloatField(max_length=120)),
                ('genre', models.DurationField()),
                ('id_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmo.director')),
                ('id_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmo.script')),
            ],
        ),
    ]
