# Generated by Django 4.1.7 on 2023-02-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
