# Generated by Django 4.1.7 on 2023-02-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmo', '0003_rename_lastaname_director_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='script',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
