# Generated by Django 4.1.7 on 2023-02-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmo', '0004_alter_movie_description_alter_script_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'action'), ('SUSPENSE', 'suspense'), ('HORROR', 'horror'), ('ROMANTIC', 'romantic'), ('COMEDY', 'comedy'), ('UNDEFINED', 'undefined')], max_length=120),
        ),
    ]
