# Generated by Django 4.1.7 on 2023-02-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmo', '0006_alter_movie_id_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(to='filmo.movie'),
        ),
    ]
