# Generated by Django 4.1.7 on 2023-02-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmo', '0007_actor_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.AddField(
            model_name='play',
            name='id_actor',
            field=models.ManyToManyField(to='filmo.actor'),
        ),
        migrations.AddField(
            model_name='play',
            name='id_movies',
            field=models.ManyToManyField(to='filmo.movie'),
        ),
    ]
